# Generated by Django 3.2.13 on 2022-08-07 09:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(default='booking/images/default.png', upload_to='booking/images')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('average_area', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(default='booking/images/default.png', upload_to='booking/images')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-average_area',),
            },
        ),
        migrations.CreateModel(
            name='RoomSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_area', models.FloatField()),
                ('default_capacity', models.IntegerField()),
                ('default_price', models.FloatField()),
                ('image', models.ImageField(default='booking/images/default.png', upload_to='booking/images')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.roomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('area', models.FloatField(default=0.0)),
                ('capacity', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('price', models.FloatField()),
                ('state', models.CharField(choices=[('booked', 'Booked'), ('in_used', 'In Used'), ('cleaning', 'Cleaning'), ('available', 'Available')], default='available', max_length=30)),
                ('image', models.ImageField(default='booking/images/default.png', upload_to='booking/images')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.roomsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('id_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
