# Generated by Django 3.2.13 on 2022-08-07 17:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('done', 'Done'), ('cancel', 'Cancel')], max_length=20)),
                ('note', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('count_guests', models.IntegerField()),
                ('booking_request_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.bookingrequest')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room')),
            ],
        ),
    ]
