# Generated by Django 3.2.13 on 2022-08-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220807_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
    ]
