# Generated by Django 4.1 on 2022-08-17 02:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_amenity_alter_room_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(default='booking/images/default.png', upload_to='booking/images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.roomsubcategory')),
            ],
        ),
    ]
