# Generated by Django 4.1 on 2022-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsubcategory',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
