# Generated by Django 4.1 on 2022-08-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_roomsubcategory_viewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
